-- todo_list.task
	CREATE TABLE IF NOT EXISTS todo_list.`task` (
		`task_id` BIGINT NOT NULL AUTO_INCREMENT,
		`task_name` VARCHAR(100) NOT NULL,
		`task_description` VARCHAR(255) NOT NULL,
		`task_author` VARCHAR(36) NOT NULL,
		`task_categori` ENUM('WORK','STUDY','PERSONAL') NOT NULL COMMENT "NOT MORE RELATIONSHIP WITH CATEGORI ENTITY",
		`task_tag` ENUM('URGENT','IMPORTANT','OPTIONAL') NOT NULL COMMENT "ADD TAG ENTITY RELATIONSHIP ON BACKLOG",
		`task_created_at` DATETIME(3) NOT NULL COMMENT "ADD DATE TYPE ON BACKLOG",
		`task_update_at` DATETIME(3) COMMENT "ADD DATE TYPE ON BACKLOG",
		`task_is_done` TINYINT(1) NOT NULL,
		PRIMARY KEY (`task_id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;